# Generated by Django 5.1.1 on 2024-10-08 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_days(apps, schema_editor):
    Day = apps.get_model('erp', 'Day')
    days_of_week = ['Dushanba', 'Seshanba', 'Chorshanba', 'Payshanba', 'Juma', 'Shanba', 'Yakshanba']
    
    for day_name in days_of_week:
        Day.objects.create(name=day_name)


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('max_students', models.IntegerField(default=30)),
                ('room', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas')], default='active', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.course')),
                ('days', models.ManyToManyField(to='erp.day')),
                ('students', models.ManyToManyField(blank=True, related_name='student_groups', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_initial_days),
    ]
