# Generated by Django 5.1.1 on 2024-10-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_course_day_alter_user_email_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Salom ', max_length=128),
            preserve_default=False,
        ),
    ]
