# Generated by Django 5.1.1 on 2024-10-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_group_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='group',
            name='room',
        ),
    ]
